# Generated by Django 2.1.5 on 2019-08-26 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Materias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materias',
            name='tipo',
            field=models.CharField(default='UNI', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='materias',
            name='carrera',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Carreras.Carreras'),
        ),
    ]
