# Generated by Django 2.1.5 on 2019-08-03 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maestros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('titulo', models.CharField(max_length=150, unique=True)),
                ('celula', models.CharField(max_length=150, unique=True)),
                ('institucion', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=11)),
                ('direccion', models.TextField()),
                ('sexo', models.CharField(max_length=10)),
                ('edad', models.IntegerField()),
                ('nacimiento', models.DateField()),
                ('correo', models.CharField(max_length=150)),
                ('tipo', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'Maestros',
            },
        ),
    ]
