# Generated by Django 2.1.5 on 2019-08-03 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Maestros', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maestros',
            old_name='celula',
            new_name='cedulaprofesional',
        ),
        migrations.RenameField(
            model_name='maestros',
            old_name='nacimiento',
            new_name='fechadenacimiento',
        ),
        migrations.RenameField(
            model_name='maestros',
            old_name='institucion',
            new_name='institucioneducativa',
        ),
        migrations.RemoveField(
            model_name='maestros',
            name='titulo',
        ),
        migrations.AddField(
            model_name='maestros',
            name='apellidomaterno',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maestros',
            name='apellidopaterno',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maestros',
            name='tituloprofesional',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='maestros',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
