# Generated by Django 2.1.5 on 2019-08-14 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Maestros', '0004_auto_20190813_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='maestros',
            name='estado',
            field=models.CharField(default='Activo', max_length=150),
            preserve_default=False,
        ),
    ]
