# Generated by Django 2.1.5 on 2019-08-03 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Grupos', '0001_initial'),
        ('Carreras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumnos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('matricula', models.CharField(max_length=15, unique=True)),
                ('curp', models.CharField(max_length=20, unique=True)),
                ('estatus', models.CharField(max_length=20)),
                ('edad', models.IntegerField()),
                ('sexo', models.CharField(max_length=20)),
                ('nacimiento', models.DateField()),
                ('folio_certificado', models.CharField(max_length=30)),
                ('direccion', models.TextField()),
                ('colonia', models.TextField()),
                ('modalidad', models.CharField(max_length=30)),
                ('telefono', models.CharField(max_length=11)),
                ('tutor', models.CharField(max_length=150)),
                ('certificado', models.IntegerField()),
                ('certificado_copias', models.IntegerField()),
                ('acta_nacimiento', models.IntegerField()),
                ('acta_nacimiento_copia', models.IntegerField()),
                ('ine_copias', models.IntegerField()),
                ('comprobante_domicilio', models.IntegerField()),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Carreras.Carreras')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Grupos.Grupos')),
            ],
            options={
                'db_table': 'Alumnos',
            },
        ),
    ]
