# Generated by Django 2.1.5 on 2019-08-13 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Alumnos', '0002_auto_20190803_1802'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumnos',
            old_name='acta_nacimiento_copia',
            new_name='acta_de_nacimiento_tres_copias',
        ),
        migrations.RenameField(
            model_name='alumnos',
            old_name='certificado',
            new_name='certificado_original',
        ),
        migrations.RenameField(
            model_name='alumnos',
            old_name='certificado_copias',
            new_name='certificado_tres_copias',
        ),
        migrations.RenameField(
            model_name='alumnos',
            old_name='comprobante_domicilio',
            new_name='comprobante_de_domicilio',
        ),
        migrations.RenameField(
            model_name='alumnos',
            old_name='estatus',
            new_name='estado',
        ),
        migrations.RenameField(
            model_name='alumnos',
            old_name='nacimiento',
            new_name='fechadenacimiento',
        ),
        migrations.RenameField(
            model_name='alumnos',
            old_name='ine_copias',
            new_name='ine_tres_copias',
        ),
        migrations.RenameField(
            model_name='alumnos',
            old_name='colonia',
            new_name='municipio',
        ),
        migrations.AlterField(
            model_name='alumnos',
            name='carrera',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Carreras.Carreras'),
        ),
    ]
