# Generated by Django 2.1.5 on 2019-08-14 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alumnos', '0003_auto_20190813_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumnos',
            name='tipo',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
