# Generated by Django 2.1.5 on 2019-08-14 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alumnos', '0004_alumnos_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnos',
            name='tutor',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
