# Generated by Django 2.1.5 on 2019-08-13 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grupos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupos',
            name='modalidad',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
