# Generated by Django 2.1.5 on 2019-08-14 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Grupos', '0002_grupos_modalidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupos',
            name='modalidad',
        ),
    ]
