# Generated by Django 2.1.5 on 2019-08-17 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Maestros', '0005_maestros_estado'),
        ('Materias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MateriasAsignadas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('inicio_modulo', models.DateField()),
                ('fin_modulo', models.DateField()),
                ('horas_semanales', models.IntegerField()),
                ('pagado', models.BooleanField(default=False)),
                ('maestro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Maestros.Maestros')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Materias.Materias')),
            ],
            options={
                'db_table': 'MateriasAsignadas',
            },
        ),
    ]
