# Generated by Django 2.1.5 on 2019-08-17 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MateriasAsignadas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materiasasignadas',
            name='nombre',
        ),
    ]
