# Generated by Django 2.1.5 on 2019-08-03 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carreras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('nomenclatura', models.CharField(max_length=15, unique=True)),
                ('tipo', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'Carreras',
            },
        ),
    ]
