# Generated by Django 2.1.5 on 2019-08-26 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Carreras', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carreras',
            name='tipo',
        ),
    ]
