# Generated by Django 2.1.5 on 2019-08-19 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('MateriasAsignadas', '0002_remove_materiasasignadas_nombre'),
        ('Alumnos', '0005_auto_20190814_1510'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calificaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.FloatField()),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Alumnos.Alumnos')),
                ('materia_asignada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MateriasAsignadas.MateriasAsignadas')),
            ],
            options={
                'db_table': 'Calificaciones',
            },
        ),
    ]
